import { ConfigService } from '@nestjs/config';
import { timingSafeEqual } from 'crypto';
import { CookieOptions } from 'express';

export const OAUTH_STATE_COOKIE_NAME = 'oauth_state';

export const OAUTH_STATE_MAX_AGE_MS = 10 * 60 * 1000;

// `<locale>.<nonce>`: the nonce is generated by the web app (≥ 32 bytes of
// base64url) and bound to the browser through a cookie on both domains, so a
// callback URL crafted by someone else cannot complete the login (login CSRF).
const OAUTH_STATE_PATTERN = /^([A-Za-z-]{2,10})\.([A-Za-z0-9_-]{43,128})$/;

export interface OAuthState {
  locale: string;
  nonce: string;
}

export function parseOAuthState(state: unknown): OAuthState | null {
  if (typeof state !== 'string') {
    return null;
  }

  const match = OAUTH_STATE_PATTERN.exec(state);
  return match ? { locale: match[1], nonce: match[2] } : null;
}

export function oauthStatesMatch(expected: unknown, actual: unknown): boolean {
  if (typeof expected !== 'string' || typeof actual !== 'string') {
    return false;
  }

  const expectedBuffer = Buffer.from(expected);
  const actualBuffer = Buffer.from(actual);
  return (
    expectedBuffer.length === actualBuffer.length &&
    timingSafeEqual(expectedBuffer, actualBuffer)
  );
}

// SameSite must stay `lax`: the callback is a top-level cross-site redirect
// from Google, which `strict` cookies would not survive.
export function createOAuthStateCookieOptions(
  config: ConfigService,
): CookieOptions {
  return {
    httpOnly: true,
    path: '/',
    sameSite: 'lax',
    // Secure by default, same rule as the access_token cookie.
    secure: config.get<string>('COOKIE_SECURE', 'true') !== 'false',
  };
}
